name: go-build
on:
  push:
    branches:
      - main
    paths:
      - '*.go'
      - 'go.*'
      - '.github/workflows/build.yaml'

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: ko-build/setup-ko@v0.7
        env:
          KO_DOCKER_REPO: docker.io/thisisnttheway/igc-merger
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: thisisnttheway
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - run: ko build --base-import-paths